/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  plugins: ["stylelint-order"],
  rules: {
    "scss/load-partial-extension": null,
    "scss/at-import-partial-extension": null,
    "scss/at-use-no-unnamespaced": null,
    "property-no-vendor-prefix": null,
    "scss/at-extend-no-missing-placeholder": null,
    "font-family-no-missing-generic-family-keyword": null,
    "media-feature-range-notation": null,
    "selector-pseudo-class-no-unknown": [
      true,
      {
        ignorePseudoClasses: ["global", "local"],
      },
    ],
    "selector-class-pattern": [
      "^_?[a-z][a-zA-Z0-9]*$|^_?[A-Z][a-zA-Z0-9]*$",
      {
        message:
          "Классы должны быть в camelCase или PascalCase (допустим `_` в начале)",
        resolveNestedSelectors: false,
      },
    ],
    "rule-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["after-comment"],
      },
    ],
    "at-rule-empty-line-before": [
      "always",
      {
        except: ["first-nested", "blockless-after-same-name-blockless"],
        ignore: ["after-comment"],
      },
    ],
    "scss/at-mixin-pattern": "^([a-z][a-z0-9-]*|[a-z][a-zA-Z0-9]*)$",

    "order/properties-order": [
      [
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "z-index",

        "display",
        "flex",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "flex-direction",
        "flex-wrap",
        "justify-content",
        "align-items",
        "align-content",
        "order",

        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",

        "border",
        "border-width",
        "border-style",
        "border-color",
        "border-radius",

        "background",
        "background-color",
        "background-image",
        "background-position",
        "background-size",
        "background-repeat",
        "box-shadow",
        "opacity",

        "font",
        "font-family",
        "font-size",
        "font-weight",
        "line-height",
        "letter-spacing",
        "text-align",
        "text-decoration",
        "text-transform",
        "color",

        "transition",
        "transition-delay",
        "transition-duration",
        "transition-property",
        "transition-timing-function",
        "transform",
        "animation",
        "animation-delay",
        "animation-duration",
        "animation-iteration-count",
        "animation-name",
        "animation-timing-function",

        "cursor",
        "visibility",
        "overflow",
        "overflow-x",
        "overflow-y",
        "pointer-events",
        "user-select",
      ],
      {
        unspecified: "bottomAlphabetical",
        severity: "warning",
      },
    ],
  },
  ignoreFiles: ["src/shared/styles/**/*"],
};
